/**
 * This file defines the layout of the app.
 */

import type { Metadata } from 'next';
import { Plus_Jakarta_Sans } from 'next/font/google';
import './globals.css';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { config } from '@fortawesome/fontawesome-svg-core';
config.autoAddCss = false;

// Set the font family for Plus Jakarta Sans
const plusJakartaSans = Plus_Jakarta_Sans({ subsets: ['latin'] });

// Define the metadata
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

/**
 * A description of the entire function.
 *
 * @param {Readonly<{ children: React.ReactNode; }>} children - The child elements to be rendered.
 * @return {JSX.Element} The rendered HTML body element.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html lang='en'>
      <body className={plusJakartaSans.className}>{children}</body>
    </html>
  );
}
